package co.edu.udea.ingenieriaweb.xsoftbackend.dto;
// Generated 28/05/2015 11:07:23 PM by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private ClienteId id;
     private Tipodocumento tipodocumento;
     private String nombres;
     private String apellidos;
     private String telefonoFijo;
     private String telefonoMovil;
     private String email;
     private String direccion;

    public Cliente() {
    }

    public Cliente(ClienteId id, Tipodocumento tipodocumento, String nombres, String apellidos, String telefonoFijo, String telefonoMovil, String email, String direccion) {
       this.id = id;
       this.tipodocumento = tipodocumento;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefonoFijo = telefonoFijo;
       this.telefonoMovil = telefonoMovil;
       this.email = email;
       this.direccion = direccion;
    }
   
    public ClienteId getId() {
        return this.id;
    }
    
    public void setId(ClienteId id) {
        this.id = id;
    }
    public Tipodocumento getTipodocumento() {
        return this.tipodocumento;
    }
    
    public void setTipodocumento(Tipodocumento tipodocumento) {
        this.tipodocumento = tipodocumento;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }
    
    public void setTelefonoMovil(String telefonoMovil) {
        this.telefonoMovil = telefonoMovil;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }




}


