package co.edu.udea.ingenieriaweb.xsoftbackend.dto;


import java.util.HashSet;
import java.util.Set;

/**
 * Tipodocumento generated by hbm2java
 */
public class Tipodocumento  implements java.io.Serializable {


     private Integer idTipoDocumento;
     private String nombre;
     private String abreviatura;
     private Set clientes = new HashSet(0);

    public Tipodocumento() {
    }

	
    public Tipodocumento(String nombre, String abreviatura) {
        this.nombre = nombre;
        this.abreviatura = abreviatura;
    }
    public Tipodocumento(String nombre, String abreviatura, Set clientes) {
       this.nombre = nombre;
       this.abreviatura = abreviatura;
       this.clientes = clientes;
    }
   
    public Integer getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(Integer idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


