package co.edu.udea.ingenieriaweb.xsoftbackend.dto;



import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private String idCliente;
     private String idUsuario;
     private Set serviciosventas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(String idCliente, String idUsuario) {
        this.idCliente = idCliente;
        this.idUsuario = idUsuario;
    }
    public Venta(String idCliente, String idUsuario, Set serviciosventas) {
       this.idCliente = idCliente;
       this.idUsuario = idUsuario;
       this.serviciosventas = serviciosventas;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Set getServiciosventas() {
        return this.serviciosventas;
    }
    
    public void setServiciosventas(Set serviciosventas) {
        this.serviciosventas = serviciosventas;
    }




}


